# Generated by Django 4.2.6 on 2023-10-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Backgroup Image')),
                ('client', models.CharField(max_length=50)),
                ('client_logo', models.ImageField(upload_to='about_us/', verbose_name='First Image')),
            ],
            options={
                'verbose_name': 'about us ',
                'verbose_name_plural': 'about us ',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/%y/%m/%d/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('from_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=9)),
                ('message', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client contact',
                'verbose_name_plural': 'Client contacts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('facebook', models.URLField(verbose_name='facebook Link')),
                ('linkedin', models.URLField(verbose_name='linkedin Link')),
                ('skype', models.URLField(verbose_name='skype Link')),
                ('instagram', models.URLField(verbose_name='instagram Link')),
                ('image', models.ImageField(upload_to='chef/')),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squad',
            },
        ),
    ]
