# Generated by Django 4.2.6 on 2023-10-13 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='about_us/', verbose_name='Backgroup Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about_us/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='client_logo',
            field=models.ImageField(upload_to='about_us/'),
        ),
    ]
