# Generated by Django 4.2.6 on 2023-10-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_client_alter_contact_options_remove_aboutus_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='client_logo',
        ),
    ]
