# Generated by Django 4.2.6 on 2023-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_remove_aboutus_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(upload_to='client/', verbose_name='Backgroup Image'),
        ),
    ]
